module Token
  class Date
    include Token::Base
    include Token::Composite

    MONTH_WORDS = [::Date::MONTHNAMES, ::Date::ABBR_MONTHNAMES].compact
    DAY_WORDS = [::Date::DAYNAMES, ::Date::ABBR_DAYNAMES].compact
    TIME_ZONES = %w{
      ACDT ACST ACT ACWST ADT AEDT AEST AET AFT AKDT AKST ALMT AMST AMT ANAT
      AQTT ART AST AWST AZOST AZOT AZT BDT BIOT BIT BOT BRST BRT BST BTT CAT
      CCT CDT CEST CET CHADT CHAST CHOT CHOST CHST CHUT CIST CIT CKT CLST CLT
      COST COT CST CT CVT CWST CXT DAVT DDUT DFT EASST EAST EAT ECT EDT EEST
      EET EGST EGT EIT EST FET FJT FKST FKT FNT GALT GAMT GET GFT GILT GIT GMT
      GST GYT HDT HAEC HST HKT HMT HOVST HOVT ICT IDLW IDT IOT IRDT IRKT IRST
      IST JST KALT KGT KOST KRAT KST LHST LINT MAGT MART MAWT MDT MET MEST MHT
      MIST MIT MMT MSK MST MUT MVT MYT NCT NDT NFT NOVT NPT NST NT NUT NZDT
      NZST OMST ORAT PDT PET PETT PGT PHOT PHT PKT PMDT PMST PONT PST PYST PYT
      RET ROTT SAKT SAMT SAST SBT SCT SDT SGT SLST SRET SRT SST SYOT TAHT THA
      TFT TJT TKT TLT TMT TRT TOT TVT ULAST ULAT UTC UYST UYT UZT VET VLAT VOLT
      VOST VUT WAKT WAST WAT WEST WET WIT WGST WGT WST YAKT YEKT
    }

    WORD_BOUNDARY_REGEXP = /\b/
    DAY_WORDS_REGEXP = /^(#{DAY_WORDS.join('|')})$/i
    MONTH_WORDS_REGEXP = /^(#{MONTH_WORDS.join('|')})$/i
    ORDINAL_DAY_REGEXP = /^\d{1,2}(?:st|nd|rd|th)$/
    ONE_OR_TWO_DIGIT_REGEXP = /^\d{1,2}$/
    FOUR_DIGIT_YEAR_REGEXP = /^[1-9]\d{3}$/
    TIMEZONE_REGEXP = /^(#{TIME_ZONES.join('|')})$/

    private

    def substring_array
      value.split(WORD_BOUNDARY_REGEXP)
    end

    def token_class(substring)
      case substring
      when MONTH_WORDS_REGEXP
        Token::MonthWord
      when DAY_WORDS_REGEXP
        Token::DayWord
      when FOUR_DIGIT_YEAR_REGEXP
        Token::Year
      when ORDINAL_DAY_REGEXP
        Token::OrdinalDay
      when ONE_OR_TWO_DIGIT_REGEXP
        Token::NumericalDate
      when TIMEZONE_REGEXP
        Token::Timezone
      else
        Token::String
      end
    end
  end
end
